name: freeczx
description: "Um aplicativo de música completo."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audioplayers: ^6.0.0
  path_provider: ^2.1.4
  http: ^1.2.2
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
